// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { env } from "node:process";
import { defineConfig } from "prisma/config"

export default defineConfig({
  datasource: {
    url: env.DATABASE_URL,
  },
  migrations: {
    seed: "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts",
  },
  //   datasource: {
  //    url: process.env["DATABASE_URL"],
  //   },
})
