/* eslint-disable @typescript-eslint/no-explicit-any */
import { notFound } from "next/navigation";
import { PrismaClient } from "@prisma/client";
import { parseGenerationResult } from "@/lib/parsers";
import { MCQResultDisplay } from "@/components/dashboard/results/mcq-result";
import { FlashcardsResultDisplay } from "@/components/dashboard/results/flashcards-result";
import { SummaryResultDisplay } from "@/components/dashboard/results/summary-result";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Zap, ArrowRight } from "lucide-react";

// Utilise une instance Prisma fraîche pour les pages publiques
// Évite les problèmes de singleton dans les Server Components externes
const prisma = new PrismaClient();

export async function generateMetadata({
  params,
}: {
  params: { token: string };
}) {
  try {
    const generation = await prisma.generation.findUnique({
      where: { shareToken: params.token },
      select: { mode: true },
    });

    if (!generation) return { title: "Not Found · QuizForge AI" };

    return {
      title: `${generation.mode} · QuizForge AI`,
      description: `View this ${generation.mode.toLowerCase()} generated by QuizForge AI`,
    };
  } catch {
    return { title: "QuizForge AI" };
  }
}

const modeConfig = {
  MCQ: {
    label: "MCQ Quiz",
    color: "bg-blue-100 text-blue-700 border-blue-200",
  },
  FLASHCARDS: {
    label: "Flashcards",
    color: "bg-violet-100 text-violet-700 border-violet-200",
  },
  SUMMARY: {
    label: "Summary",
    color: "bg-emerald-100 text-emerald-700 border-emerald-200",
  },
};

export default async function SharePage({
  params,
}: {
  params: { token: string };
}) {
  let generation = null;

  try {
    generation = await prisma.generation.findUnique({
      where: { shareToken: params.token },
      select: {
        id: true,
        outputText: true,
        mode: true,
        language: true,
        createdAt: true,
      },
    });
  } catch (error) {
    console.error("Share page prisma error:", error);
    notFound();
  } finally {
    await prisma.$disconnect();
  }

  if (!generation || !generation.outputText) {
    notFound();
  }

  const result = parseGenerationResult(generation.outputText, generation.mode);
  const config = modeConfig[generation.mode];

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 bg-violet-600 rounded-lg flex items-center justify-center">
              <Zap className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="font-bold text-slate-900 text-sm">
              QuizForge AI
            </span>
          </Link>
          <Link href="/register">
            <Button
              size="sm"
              className="bg-violet-600 hover:bg-violet-700 text-white text-xs h-8"
            >
              Create your own
              <ArrowRight className="w-3 h-3 ml-1.5" />
            </Button>
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 py-8">
        {/* Meta */}
        <div className="mb-6">
          <div className="flex items-center gap-2 mb-1">
            <Badge variant="outline" className={`text-xs ${config.color}`}>
              {config.label}
            </Badge>
            <span className="text-slate-400 text-xs">
              {new Date(generation.createdAt).toLocaleDateString("fr-FR", {
                day: "numeric",
                month: "long",
                year: "numeric",
              })}
            </span>
          </div>
          <h1 className="text-xl font-bold text-slate-900">
            Shared {config.label}
          </h1>
        </div>

        {/* Result */}
        {result ? (
          <>
            {generation.mode === "MCQ" && (
              <MCQResultDisplay data={result as any} />
            )}
            {generation.mode === "FLASHCARDS" && (
              <FlashcardsResultDisplay data={result as any} />
            )}
            {generation.mode === "SUMMARY" && (
              <SummaryResultDisplay data={result as any} />
            )}
          </>
        ) : (
          <div className="bg-white rounded-2xl border border-slate-200 p-8 text-center">
            <p className="text-slate-500">Could not display this content.</p>
          </div>
        )}

        {/* CTA Banner */}
        <div className="mt-8 bg-slate-950 rounded-2xl p-6 flex items-center justify-between gap-4">
          <div>
            <p className="text-white font-semibold mb-1">
              Create your own AI quizzes for free
            </p>
            <p className="text-slate-400 text-sm">
              Generate MCQ, Flashcards, and Summaries from any content.
            </p>
          </div>
          <Link href="/register" className="shrink-0">
            <Button className="bg-violet-600 hover:bg-violet-700 text-white">
              Get started free
              <ArrowRight className="w-4 h-4 ml-2" />
            </Button>
          </Link>
        </div>
      </main>
    </div>
  );
}
